id = "noirtech"
name = "NoirTech Theme"
version = "0.1"
schema_version = 1
authors = ["Grant <madebygrant.com>"]
description = "A dark theme that envelops your code in an inky blackness, punctuated by flashes of white, muted blues and cyan."
repository = "https://github.com/madebygrant/zed-noirtech"
